'use strict';
(function(){
  const cfg=window.LBG_SUPABASE_CONFIG;
  if(!cfg||!cfg.enabled)return;
  const q=id=>document.getElementById(id),txt=v=>String(v??'').trim(),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const api={client:null,session:null,profile:null,readyHandlers:[],logoutHandlers:[],onReady(fn){this.readyHandlers.push(fn);if(this.profile)fn(this)},onLogout(fn){this.logoutHandlers.push(fn)},isOwner(){return this.profile?.role==='owner'},canUploadShared(){return this.isOwner()||this.profile?.role==='uploader'||this.profile?.can_upload_shared}};
  window.LBGAuth=api;

  function load(src,id){return new Promise((ok,no)=>{if(q(id))return ok();const s=document.createElement('script');s.id=id;s.src=src;s.onload=ok;s.onerror=()=>no(new Error('Không tải được thư viện đăng nhập.'));document.head.appendChild(s)})}
  function style(){if(q('lbgAuthCoreStyle'))return;const s=document.createElement('style');s.id='lbgAuthCoreStyle';s.textContent=`body.lbg-auth-locked{overflow:hidden}.lbg-auth-gate,.lbg-password-gate{position:fixed;inset:0;z-index:99999;background:linear-gradient(135deg,#082f49,#0f766e 65%,#16a34a);display:grid;place-items:center;padding:18px}.lbg-login-box{width:min(440px,100%);background:#fff;border-radius:24px;padding:26px;box-shadow:0 24px 80px #001a}.lbg-login-box h2{margin:0 0 6px;color:#082f49}.lbg-login-box p{margin:0 0 18px;color:#64748b}.lbg-login-box label{display:grid;gap:6px;margin:12px 0;font-size:13px;font-weight:750}.lbg-login-box input{padding:11px 12px;border:1px solid #dbe6eb;border-radius:11px;font:inherit}.lbg-auth-actions{display:flex;gap:9px;margin-top:16px}.lbg-auth-msg{min-height:22px;margin-top:10px;font-size:12px;color:#b91c1c}.lbg-userbar{position:sticky;top:73px;z-index:9;max-width:1450px;margin:auto;padding:8px 24px;display:flex;gap:8px;justify-content:flex-end;align-items:center}.lbg-userchip{background:#fff;border:1px solid #dbe6eb;border-radius:999px;padding:7px 11px;font-size:12px;box-shadow:0 8px 24px #082f4912}.lbg-role-hidden{display:none!important}@media(max-width:760px){.lbg-userbar{top:65px;padding:7px 13px;flex-wrap:wrap}}`;document.head.appendChild(s)}
  function emailOf(username){return `${txt(username).toLowerCase()}@${cfg.usernameDomain||'users.lichbaogiang.internal'}`}
  function roleName(role){return role==='owner'?'Chủ sở hữu':role==='uploader'?'Được tải TKB chung':'Người dùng'}
  function gate(){if(q('lbgAuthGate'))return;document.body.classList.add('lbg-auth-locked');const d=document.createElement('div');d.id='lbgAuthGate';d.className='lbg-auth-gate';d.innerHTML=`<form class="lbg-login-box" id="lbgLoginForm"><h2>🔐 Đăng nhập Lịch Báo giảng</h2><p>Nhập mã tài khoản và mật khẩu do chủ sở hữu cấp.</p><label>Mã đăng nhập<input id="lbgLoginUser" maxlength="32" autocomplete="username" placeholder="Ví dụ: GV001" required></label><label>Mật khẩu<input id="lbgLoginPass" type="password" autocomplete="current-password" required></label><div class="lbg-auth-actions"><button class="btn primary" id="lbgLoginBtn">Đăng nhập</button><button class="btn outline" type="button" id="lbgShowPass">Hiện mật khẩu</button></div><div id="lbgLoginMsg" class="lbg-auth-msg"></div></form>`;document.body.appendChild(d);q('lbgShowPass').onclick=()=>{const p=q('lbgLoginPass');p.type=p.type==='password'?'text':'password';q('lbgShowPass').textContent=p.type==='password'?'Hiện mật khẩu':'Ẩn mật khẩu'};q('lbgLoginForm').onsubmit=login}
  function closeGate(){q('lbgAuthGate')?.remove();document.body.classList.remove('lbg-auth-locked')}
  async function login(e){e.preventDefault();const b=q('lbgLoginBtn'),old=b.textContent,msg=q('lbgLoginMsg');b.disabled=true;b.textContent='Đang đăng nhập…';msg.textContent='';try{const username=txt(q('lbgLoginUser').value).toLowerCase();if(!/^[a-z0-9._-]{3,32}$/.test(username))throw new Error('Mã đăng nhập không hợp lệ.');const {data,error}=await api.client.auth.signInWithPassword({email:emailOf(username),password:q('lbgLoginPass').value});if(error)throw error;await accept(data.session)}catch(e){msg.textContent=e?.message==='Invalid login credentials'?'Sai mã đăng nhập hoặc mật khẩu.':e?.message||String(e)}finally{b.disabled=false;b.textContent=old}}
  async function profileFor(session){const {data,error}=await api.client.from('profiles').select('*').eq('id',session.user.id).single();if(error)throw error;if(!data.is_active)throw new Error('Tài khoản đã bị khóa.');if(data.expires_at&&new Date(data.expires_at)<=new Date())throw new Error('Tài khoản đã hết hạn.');return data}
  async function accept(session){api.session=session;if(!session){api.profile=null;gate();api.logoutHandlers.forEach(fn=>fn(api));return}try{api.profile=await profileFor(session);await api.client.rpc('mark_login');closeGate();userbar();roleVisibility();if(api.profile.must_change_password)passwordGate(true);api.readyHandlers.forEach(fn=>fn(api))}catch(e){await api.client.auth.signOut();api.session=null;api.profile=null;gate();q('lbgLoginMsg').textContent=e?.message||String(e)}}
  function userbar(){let b=q('lbgUserBar');if(!b){b=document.createElement('div');b.id='lbgUserBar';b.className='lbg-userbar';document.querySelector('header.top')?.insertAdjacentElement('afterend',b)}b.innerHTML=`<span class="lbg-userchip"><b>${esc(api.profile.display_name||api.profile.username)}</b> • ${esc(roleName(api.profile.role))}</span><button class="btn outline mini" id="lbgChangePass">Đổi mật khẩu</button><button class="btn outline danger mini" id="lbgLogout">Đăng xuất</button>`;q('lbgChangePass').onclick=()=>passwordGate(false);q('lbgLogout').onclick=()=>api.client.auth.signOut()}
  function roleVisibility(){const owner=api.isOwner();document.querySelectorAll('button,a').forEach(el=>{if(/Google Sheets/i.test(txt(el.textContent)))el.classList.toggle('lbg-role-hidden',!owner)});document.documentElement.dataset.lbgRole=api.profile.role}
  function passwordGate(required){if(q('lbgPasswordGate'))return;const d=document.createElement('div');d.id='lbgPasswordGate';d.className='lbg-password-gate';d.innerHTML=`<form class="lbg-login-box" id="lbgPasswordForm"><h2>Đổi mật khẩu</h2><p>${required?'Bạn phải đổi mật khẩu tạm trước khi tiếp tục.':'Nhập mật khẩu mới cho tài khoản.'}</p><label>Mật khẩu mới<input id="lbgNewPass" type="password" minlength="8" autocomplete="new-password" required></label><label>Nhập lại mật khẩu<input id="lbgNewPass2" type="password" minlength="8" autocomplete="new-password" required></label><div class="lbg-auth-actions"><button class="btn primary" id="lbgSavePass">Lưu</button>${required?'':'<button class="btn outline" type="button" id="lbgCancelPass">Hủy</button>'}</div><div id="lbgPassMsg" class="lbg-auth-msg"></div></form>`;document.body.appendChild(d);q('lbgCancelPass')?.addEventListener('click',()=>d.remove());q('lbgPasswordForm').onsubmit=async e=>{e.preventDefault();const p=q('lbgNewPass').value,p2=q('lbgNewPass2').value,m=q('lbgPassMsg'),b=q('lbgSavePass');if(p.length<8){m.textContent='Mật khẩu phải có ít nhất 8 ký tự.';return}if(p!==p2){m.textContent='Hai lần nhập chưa khớp.';return}b.disabled=true;try{const {error}=await api.client.auth.updateUser({password:p});if(error)throw error;const {error:e2}=await api.client.rpc('complete_password_change');if(e2)throw e2;api.profile.must_change_password=false;d.remove();alert('Đã đổi mật khẩu thành công.')}catch(e){m.textContent=e?.message||String(e)}finally{b.disabled=false}}}
  async function init(){style();gate();try{await load('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2','lbgSupabaseJs');api.client=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});const {data}=await api.client.auth.getSession();if(data.session)await accept(data.session);api.client.auth.onAuthStateChange((_event,next)=>{if(next?.access_token===api.session?.access_token)return;setTimeout(()=>accept(next),0)})}catch(e){q('lbgLoginMsg').textContent='Không kết nối được hệ thống đăng nhập: '+(e?.message||String(e))}}
  init();
})();
