'use strict';
(function(){
  const cfg=window.LBG_SUPABASE_CONFIG;if(!cfg?.enabled||!window.LBGAuth)return;
  const q=id=>document.getElementById(id),txt=v=>String(v??'').trim(),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),MB=1024*1024;
  let auth=null,rows=[],scope='shared',timer=null;
  const fmt=n=>Number(n)<MB?`${(Number(n)/1024).toFixed(1)} KB`:`${(Number(n)/MB).toFixed(1)} MB`;
  function load(src,id){return new Promise((ok,no)=>{if(q(id))return ok();const s=document.createElement('script');s.id=id;s.src=src;s.onload=ok;s.onerror=()=>no(new Error('Không tải được thư viện tải file.'));document.head.appendChild(s)})}
  function style(){if(q('lbgCloudStyle'))return;const s=document.createElement('style');s.id='lbgCloudStyle';s.textContent=`.lbg-cloud-card{background:#fff;border:1px solid #dbe6eb;border-radius:20px;padding:19px;box-shadow:0 14px 36px rgba(8,47,73,.09);margin-top:18px}.lbg-cloud-head{display:flex;gap:12px;align-items:center;justify-content:space-between;flex-wrap:wrap}.lbg-cloud-tabs{display:flex;gap:7px;flex-wrap:wrap}.lbg-cloud-tabs button.active{background:#0f766e;color:#fff}.lbg-cloud-upload{display:grid;grid-template-columns:1fr minmax(160px,220px) auto;gap:9px;align-items:end;margin:14px 0}.lbg-cloud-upload input{width:100%;padding:10px;border:1px solid #dbe6eb;border-radius:11px}.lbg-cloud-progress{height:9px;background:#e2e8f0;border-radius:999px;overflow:hidden;display:none}.lbg-cloud-progress span{display:block;height:100%;background:#0f766e;width:0}.lbg-cloud-actions{display:flex;gap:6px;flex-wrap:wrap}.lbg-cloud-table td,.lbg-cloud-table th{white-space:normal;vertical-align:top}.lbg-cloud-note{font-size:12px;color:#64748b;margin:6px 0}@media(max-width:760px){.lbg-cloud-upload{grid-template-columns:1fr}}`;document.head.appendChild(s)}
  function access(){return window.LBGAccess?.context||{}}
  function canShared(){const c=access();return Boolean(auth?.isOwner()||c.can_upload_shared||auth?.canUploadShared?.())}
  function canActivateShared(){const c=access();return Boolean(auth?.isOwner()||c.can_activate_shared_tkb)}
  function card(){if(q('lbgCloudCard'))return;style();const main=document.querySelector('main.shell'),hero=main?.querySelector('.hero');if(!main)return;const d=document.createElement('section');d.id='lbgCloudCard';d.className='lbg-cloud-card';d.innerHTML=`<div class="lbg-cloud-head"><div><h3 style="margin:0">☁ Kho TKB đồng bộ</h3><p style="margin:3px 0;color:#64748b;font-size:12px">Kho chung và kho cá nhân tách biệt; file cá nhân không ảnh hưởng người khác.</p></div><div class="lbg-cloud-tabs"><button class="btn outline active" data-scope="shared">TKB chung</button><button class="btn outline" data-scope="personal">TKB cá nhân</button></div></div><div class="lbg-cloud-upload"><label>Chọn file<input id="lbgCloudFile" type="file" accept=".xlsx,.xlsm"></label><label>Ghi chú<input id="lbgCloudMemo" maxlength="160"></label><button class="btn primary" id="lbgCloudUpload">Tải lên</button></div><div class="lbg-cloud-progress" id="lbgCloudProgress"><span></span></div><div class="lbg-cloud-note" id="lbgCloudQuota"></div><div class="notice" id="lbgCloudStatus">Đang đồng bộ…</div><div class="wrap lbg-cloud-table"><table><thead><tr><th>File</th><th>Dung lượng</th><th>Ngày tải</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody id="lbgCloudRows"></tbody></table></div>`;hero?.insertAdjacentElement('afterend',d);d.querySelectorAll('[data-scope]').forEach(b=>b.onclick=()=>setScope(b.dataset.scope));q('lbgCloudUpload').onclick=uploadSelected;setScope('shared')}
  function setScope(value){scope=value==='personal'?'personal':'shared';q('lbgCloudCard')?.querySelectorAll('[data-scope]').forEach(b=>b.classList.toggle('active',b.dataset.scope===scope));const allowed=scope==='personal'||canShared();['lbgCloudFile','lbgCloudMemo','lbgCloudUpload'].forEach(id=>{const el=q(id);if(el)el.disabled=!allowed});render()}
  async function refresh(){const {data,error}=await auth.client.from('tkb_files').select('*').eq('status','ready').order('created_at',{ascending:false});if(error)throw error;rows=data||[];render();checkShared()}
  function render(){if(!q('lbgCloudRows'))return;const list=rows.filter(x=>x.scope===scope);q('lbgCloudRows').innerHTML=list.length?list.map(x=>`<tr><td><b>${esc(x.original_name)}</b><br><small>${esc(x.notes||'')}</small></td><td>${fmt(x.size_bytes)}</td><td>${new Date(x.created_at).toLocaleString('vi-VN')}</td><td>${x.is_active?'<span class="badge">Đang áp dụng</span>':'Bản lưu'}</td><td><div class="lbg-cloud-actions"><button class="btn outline mini" data-open="${x.id}">Mở file</button>${x.scope==='personal'?`<button class="btn outline mini" data-personal="${x.id}" ${x.is_active?'disabled':''}>Dùng bản này</button>`:''}${x.scope==='shared'&&canActivateShared()?`<button class="btn outline mini" data-shared="${x.id}" ${x.is_active?'disabled':''}>Đặt bản chung</button>`:''}<button class="btn outline danger mini" data-delete="${x.id}" ${(x.scope==='shared'&&!auth.isOwner())?'disabled':''}>Xóa</button></div></td></tr>`).join(''):'<tr><td colspan="5"><div class="empty">Chưa có file trong kho này.</div></td></tr>';q('lbgCloudRows').querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openCloud(b.dataset.open));q('lbgCloudRows').querySelectorAll('[data-personal]').forEach(b=>b.onclick=()=>activateCloud(b.dataset.personal,'personal'));q('lbgCloudRows').querySelectorAll('[data-shared]').forEach(b=>b.onclick=()=>activateCloud(b.dataset.shared,'shared'));q('lbgCloudRows').querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete));const personal=rows.filter(x=>x.scope==='personal'),used=personal.reduce((a,x)=>a+Number(x.size_bytes||0),0);if(scope==='personal')q('lbgCloudQuota').textContent=`Đã dùng ${personal.length}/20 file • ${fmt(used)}/500 MB`;else if(canShared()&&canActivateShared())q('lbgCloudQuota').textContent='Bạn được tải TKB chung và chọn bản chung đang áp dụng.';else if(canShared())q('lbgCloudQuota').textContent='Bạn được tải TKB chung nhưng không được chọn bản áp dụng.';else if(canActivateShared())q('lbgCloudQuota').textContent='Bạn được chọn TKB chung đang áp dụng nhưng không được tải bản mới.';else q('lbgCloudQuota').textContent='Bạn chỉ thấy bản TKB chung đang áp dụng.';q('lbgCloudStatus').textContent=`Đã đồng bộ ${list.length} phiên bản.`}
  function progress(p,show=true){const e=q('lbgCloudProgress');if(!e)return;e.style.display=show?'block':'none';e.firstElementChild.style.width=`${Math.max(0,Math.min(100,p))}%`}
  async function uploadSelected(){const file=q('lbgCloudFile').files?.[0];if(!file)return alert('Hãy chọn file TKB.');if(!/\.(xlsx|xlsm)$/i.test(file.name))return alert('Chỉ nhận file .xlsx hoặc .xlsm.');if(file.size>Number(cfg.maxFileBytes||50*MB))return alert('File vượt quá 50 MB.');const b=q('lbgCloudUpload'),old=b.textContent;b.disabled=true;b.textContent='Đang tải…';try{const {data:r,error}=await auth.client.rpc('reserve_tkb_upload',{p_scope:scope,p_original_name:file.name,p_size_bytes:file.size,p_mime_type:file.type||'application/octet-stream',p_notes:txt(q('lbgCloudMemo').value)});if(error)throw error;await upload(file,r.storage_path);const {error:e2}=await auth.client.rpc('finalize_tkb_upload',{p_id:r.id});if(e2)throw e2;q('lbgCloudFile').value='';q('lbgCloudMemo').value='';await refresh();alert('Đã tải TKB lên kho đồng bộ.')}catch(e){alert('Không tải được: '+(e?.message||String(e)))}finally{b.disabled=false;b.textContent=old;progress(0,false)}}
  async function upload(file,path){if(file.size<=6*MB){progress(15);const {error}=await auth.client.storage.from(cfg.bucket||'tkb-private').upload(path,file,{contentType:file.type||'application/octet-stream',upsert:false});if(error)throw error;progress(100);return}await load('https://cdn.jsdelivr.net/npm/tus-js-client@4/dist/tus.min.js','lbgTus');const {data:{session}}=await auth.client.auth.getSession();if(!session)throw new Error('Phiên đăng nhập đã hết hạn.');const ref=new URL(cfg.url).hostname.split('.')[0];await new Promise((ok,no)=>{const u=new tus.Upload(file,{endpoint:`https://${ref}.storage.supabase.co/storage/v1/upload/resumable`,retryDelays:[0,1000,3000,5000,10000],headers:{authorization:`Bearer ${session.access_token}`,apikey:cfg.publishableKey,'x-upsert':'false'},metadata:{bucketName:cfg.bucket||'tkb-private',objectName:path,contentType:file.type||'application/octet-stream',cacheControl:'3600'},chunkSize:6*MB,removeFingerprintOnSuccess:true,onError:no,onProgress:(a,b)=>progress(b?a/b*100:0),onSuccess:ok});u.findPreviousUploads().then(x=>{if(x.length)u.resumeFromPreviousUpload(x[0]);u.start()}).catch(no)})}
  async function openCloud(id){const row=rows.find(x=>x.id===id);if(!row)return;try{const localId=`cloud:${row.id}`,existing=typeof all==='function'?await all():[];if(!existing.some(x=>x.id===localId)){const {data,error}=await auth.client.storage.from(cfg.bucket||'tkb-private').download(row.storage_path);if(error)throw error;await put({id:localId,name:`☁ ${row.original_name}`,created:row.updated_at||row.created_at,size:fmt(row.size_bytes),buffer:await data.arrayBuffer()})}versions=(await all()).sort((a,b)=>b.created.localeCompare(a.created));activeId=localId;localStorage.lbgActive=localId;renderVersions();if(typeof window.activate==='function')await window.activate(localId,false);document.dispatchEvent(new CustomEvent('lbg-cloud-file-opened',{detail:{id:row.id,scope:row.scope}}));toast?.('Đã mở TKB đồng bộ.')}catch(e){alert('Không mở được file: '+(e?.message||String(e)))}}
  async function activateCloud(id,type){const {error}=await auth.client.rpc(type==='shared'?'set_active_shared_tkb':'set_active_personal_tkb',{p_id:id});if(error)return alert(error.message);await refresh();await openCloud(id)}
  async function remove(id){const row=rows.find(x=>x.id===id);if(!row||!confirm(`Xóa “${row.original_name}”?`))return;try{const {error:e1}=await auth.client.storage.from(cfg.bucket||'tkb-private').remove([row.storage_path]);if(e1)throw e1;const {error:e2}=await auth.client.from('tkb_files').delete().eq('id',id);if(e2)throw e2;await refresh()}catch(e){alert('Không xóa được: '+(e?.message||String(e)))}}
  function checkShared(){const active=rows.find(x=>x.scope==='shared'&&x.is_active);if(!active)return;const seen=localStorage.lbgSharedActiveSeen||'';if(seen&&seen!==active.id&&!auth.isOwner()&&confirm(`TKB chung đã đổi sang “${active.original_name}”. Chuyển ngay?`))openCloud(active.id);localStorage.lbgSharedActiveSeen=active.id}
  window.LBGAuth.onReady(a=>{auth=a;card();refresh().catch(e=>q('lbgCloudStatus').textContent=e.message);clearInterval(timer);timer=setInterval(()=>refresh().catch(console.error),Number(cfg.sharedPollMs||60000));document.addEventListener('lbg-access-ready',()=>{setScope(scope);render()})});
  window.LBGAuth.onLogout(()=>{clearInterval(timer);timer=null;q('lbgCloudCard')?.remove()});
})();
