'use strict';
const fs=require('fs');
const assert=require('assert');
const src=fs.readFileSync('report-branding-v1.js','utf8');
const patchLoader=fs.readFileSync('patch-runtime-loader-v1.js','utf8');
assert.match(src,/Trung tâm giáo dục kỹ năng sống Hoàn Năng/,'Phải có đúng tên trung tâm.');
assert.match(src,/lbg-report-brand-logo/,'Phải có vùng logo trên bản xem trước.');
assert.match(src,/brandWorksheet/,'Phải có xử lý chèn nhận diện vào file Excel.');
assert.match(src,/const VERSION='20260925\.1'/,'Phải dùng bản sửa merge Excel mới.');
assert.match(src,/originalMerges=mergeRangesOf\(ws\)/,'Phải chụp merge gốc trước khi chèn 3 hàng branding.');
assert.match(src,/ws\.unMergeCells\(range\)/,'Phải tháo merge gốc an toàn trước spliceRows.');
assert.match(src,/ws\.mergeCells\(shiftRange\(range,3\)\)/,'Phải khôi phục merge sau khi dịch 3 hàng.');
assert.match(src,/fitRow\(ws,14,last,96,190\)/,'Phải tự tăng chiều cao hàng địa điểm buổi chiều dài.');
assert.match(src,/horizontalCentered:true/,'Trang in phải được căn giữa ngang.');
assert.match(src,/^'use strict';/,'Module phải là JavaScript hợp lệ.');
assert.match(src,/LICH_BAO_GIANG_/,'Chỉ can thiệp file lịch báo giảng, không đụng các file Excel khác.');
assert.match(src,/\.zip\$/,'Phải xử lý cả chế độ xuất ZIP nhiều giáo viên.');
assert.match(patchLoader,/report-branding-v1\.js\?v=20260925\.1/,'Patch loader phải nạp module nhận diện mới.');
console.log('OK report branding: logo + tên Hoàn Năng cho preview và file xuất');
