const fs=require('fs'),vm=require('vm'),assert=require('assert');
const code=fs.readFileSync('sheets-atomic-payload-v2.js','utf8');
const assignments=[];
const add=(code,address,period,classRaw,groupNote='')=>assignments.push({code,address,period,day:2,session:'Sáng',schoolName:'THỦY PHƯƠNG',locationKey:'TP|',className:classRaw.replace(/\s*-\s*TIẾT\s*\d+\s*$/i,''),classRaw,groupNote});
add('ĐỨC','E176',1,'4/1 + 4/2 + 4/3 + 4/4 - TIẾT 4','TIẾT 4');
add('ĐỨC','F176',2,'4/1 + 4/2 + 4/3 + 4/4 - TIẾT 4','TIẾT 4');
add('ĐỨC+','K172',3,'4/6');
for(let i=0;i<13;i++)add('ĐỨC',`X${i+1}`,((i%5)+1),`LỚP ${i+1}`);
const ws={};
const client={functions:{invoke:(name,options)=>Promise.resolve({name,body:options.body})}};
const context={console,setTimeout,clearTimeout,setInterval,clearInterval,window:{LBGAuth:{client,onReady:()=>{}},LBGTkbParserV2:{scanAssignments:()=>assignments}},document:{readyState:'complete',addEventListener:()=>{},getElementById:()=>({value:'7T9'})},wb:{getWorksheet:()=>ws}};
context.global=context;vm.createContext(context);vm.runInContext(code,context);
const api=context.window.LBGSheetsAtomicPayloadV2;assert(api,'missing API');
const body=api.normalizeBody({teacherCode:'ĐỨC',sourceSheet:'7T9',entries:[]});
assert.equal(body.entries.length,16);
assert.equal(body.mainPeriods,15);
assert.equal(body.plusPeriods,1);
assert.equal(body.total,16);
assert.equal(body.entries[0].period,4);
assert.equal(body.entries[1].period,4);
assert.equal(body.entries[0].sourceCell,'');
assert.equal(body.entries[1].sourceCell,'');
assert.equal(body.entries.filter(x=>x.sourceCode==='ĐỨC+').length,1);
console.log('OK sheets atomic payload: 15 main + 1 plus = 16, TIẾT 4 preserved');
