'use strict';
const fs=require('fs');
const assert=require('assert');
const sync=fs.readFileSync('sheets-sync-owner-v3.js','utf8');
const index=fs.readFileSync('index.html','utf8');
assert.match(sync,/const raw=txt\(e\?\.classRaw\);if\(raw\)return raw/,'Payload Google Sheets V3 phải ưu tiên classRaw đầy đủ.');
assert.match(sync,/className:raw,classRaw:raw,classBase:txt\(e\?\.className\)/,'className/classRaw phải giữ nhãn đầy đủ và classBase giữ nhãn chuẩn hóa.');
assert.match(sync,/period:teachingPeriod,teachingPeriod/,'Google Sheets phải nhận period là tiết thực dạy.');
assert.match(sync,/entriesAreAtomicAssignments:true/,'Payload phải giữ từng ô mã giáo viên nguyên tử.');
assert.match(sync,/sourceCountSemantics:'atomicTeacherCodeCells'/,'Tổng tiết phải theo số ô mã nguồn.');
assert.match(index,/app-runtime-v1\.js\?v=20260909\.3/,'Runtime tổng hợp phải dùng cache key mới.');
const sample={className:'KHỐI 3 (4 LỚP)',classRaw:'KHỐI 3 (4 LỚP) - TIẾT 4'};
const fullClassName=String(sample.classRaw||sample.className).trim();
assert.strictEqual(fullClassName,'KHỐI 3 (4 LỚP) - TIẾT 4');
console.log('OK Sheets V3 class label + atomic teaching period');
