'use strict';
const fs=require('fs');
const assert=require('assert');
const sync=fs.readFileSync('sheets-sync-owner-v2.js','utf8');
const index=fs.readFileSync('index.html','utf8');
assert.match(sync,/const fullClassName=txt\(e\?\.classRaw\|\|e\?\.className\)/,'Payload Google Sheets phải ưu tiên classRaw đầy đủ.');
assert.match(sync,/className:fullClassName/,'className gửi sang Apps Script phải giữ nhãn đầy đủ.');
assert.match(sync,/classBase:txt\(e\?\.className\)/,'Vẫn phải giữ className chuẩn hóa ở classBase để tương thích về sau.');
assert.match(sync,/classRaw:fullClassName/,'classRaw phải giữ cùng nhãn đầy đủ.');
assert.match(sync,/period:teachingPeriod/,'Google Sheets phải nhận period là tiết thực dạy.');
assert.match(sync,/entriesAreTeachingEvents:true/,'Payload phải đánh dấu đang gửi sự kiện dạy thực tế.');
assert.match(index,/sheets-sync-owner-v2\.js\?v=20260907\.2/,'Index lõi vẫn có cầu nối cũ để security loader thay bằng bản mới an toàn.');
assert.match(index,/app-runtime-v1\.js\?v=20260909\.2/,'Runtime tổng hợp phải giữ đúng chuỗi cache của bản test mới.');
const sample={className:'KHỐI 3 (4 LỚP)',classRaw:'KHỐI 3 (4 LỚP) - TIẾT 4'};
const fullClassName=String(sample.classRaw||sample.className).trim();
assert.strictEqual(fullClassName,'KHỐI 3 (4 LỚP) - TIẾT 4');
console.log('OK Sheets class label + teaching period');
